In [1]:
import numpy as np
from combinations import *
from sys import getsizeof
from tqdm import tqdm

In [2]:
s = 0
s_sorted = 0
total = 0
total_sorted = 0

is_sorted = lambda a: np.all(a[:-1] <= a[1:])

for suit_sizes in bounded_compositions(12, 4, [8, 8, 8, 8]):
    print(suit_sizes, np.argsort(suit_sizes))
    prod = 1
    for ss in suit_sizes:
        prod *= comb(8, ss, exact=True)
    total += prod
    if is_sorted(suit_sizes):
        s_sorted += 1
        total_sorted += prod
    s += 1
print(s, s_sorted, total, total_sorted, comb(32, 12, exact=True))

[8 4 0 0] [2 3 1 0]
[7 5 0 0] [2 3 1 0]
[6 6 0 0] [2 3 0 1]
[5 7 0 0] [2 3 0 1]
[4 8 0 0] [2 3 0 1]
[8 3 1 0] [3 2 1 0]
[7 4 1 0] [3 2 1 0]
[6 5 1 0] [3 2 1 0]
[5 6 1 0] [3 2 0 1]
[4 7 1 0] [3 2 0 1]
[3 8 1 0] [3 2 0 1]
[8 2 2 0] [3 1 2 0]
[7 3 2 0] [3 2 1 0]
[6 4 2 0] [3 2 1 0]
[5 5 2 0] [3 2 0 1]
[4 6 2 0] [3 2 0 1]
[3 7 2 0] [3 2 0 1]
[2 8 2 0] [3 0 2 1]
[8 1 3 0] [3 1 2 0]
[7 2 3 0] [3 1 2 0]
[6 3 3 0] [3 1 2 0]
[5 4 3 0] [3 2 1 0]
[4 5 3 0] [3 2 0 1]
[3 6 3 0] [3 0 2 1]
[2 7 3 0] [3 0 2 1]
[1 8 3 0] [3 0 2 1]
[8 0 4 0] [1 3 2 0]
[7 1 4 0] [3 1 2 0]
[6 2 4 0] [3 1 2 0]
[5 3 4 0] [3 1 2 0]
[4 4 4 0] [3 0 1 2]
[3 5 4 0] [3 0 2 1]
[2 6 4 0] [3 0 2 1]
[1 7 4 0] [3 0 2 1]
[0 8 4 0] [0 3 2 1]
[7 0 5 0] [1 3 2 0]
[6 1 5 0] [3 1 2 0]
[5 2 5 0] [3 1 0 2]
[4 3 5 0] [3 1 0 2]
[3 4 5 0] [3 0 1 2]
[2 5 5 0] [3 0 1 2]
[1 6 5 0] [3 0 2 1]
[0 7 5 0] [0 3 2 1]
[6 0 6 0] [1 3 0 2]
[5 1 6 0] [3 1 0 2]
[4 2 6 0] [3 1 0 2]
[3 3 6 0] [3 0 1 2]
[2 4 6 0] [3 0 1 2]
[1 5 6 0] [3 0 1 2]
[0 6 6 0] [0 3 1 2]


In [11]:
comb(8, [1, 2, 3])

array([ 8., 28., 56.])

### Здесь тоже расчёты для статьи о преферансе, а также для бриджа

In [2]:
def multinomial(ns: np.array):
    result = 1
    i = ns.sum()
    for n in ns[:-1]:
        for j in range(1, n + 1):
            result *= i
            result //= j
            i -= 1
    return result

In [3]:
def is_sorted(comp):
    for i in range(len(comp) - 1):
        if comp[i] > comp[i+1]:
            return False
    return True
    
def count_bounded_compositions_visiting(n, bounds: list, ordered=False):
    s = len(bounds)
    result = 0
    for comp in bounded_compositions_gray(n, bounds):
        if not ordered or is_sorted(comp):
            result +=1
    return result

In [4]:
def count_bounded_compositions(n, bounds: list):
    s = len(bounds)
    d = np.zeros((n + 1, s + 1), dtype=np.int32)
    d[:, 0] = 0
    d[0, :] = 1
    for k in range(1, s + 1):
        value = d[0, k-1]
        for j in range(1, n + 1):
            value += d[j, k - 1]
            if j > bounds[k - 1]:
                value -= d[j - bounds[k - 1] - 1, k - 1]
            d[j, k] = value
    return int(d[n, s])

def bounded_compositions_gray(n, bounds: list):
    '''
    Returns np.array of the shape (N, s), where s = len(bounds),
    N equals to the number of all bounded combinations
    '''
    s = len(bounds)
    if s == 1:
        if n >= 0 and n <= bounds[0]:
            return np.array([n], dtype=np.int8)[:, None]
        else:
            return np.array([])
    
    result = []
    for k in range(bounds[-1] + 1):
        prev = bounded_compositions_gray(n - k, bounds[:-1])
        if prev.shape[0]:
            if k % 2 == 1:
                prev = prev[::-1]
            if len(prev) > 0:
                # print(j, k, prev)
                result.append(np.hstack((prev, k * np.ones((prev.shape[0], 1), dtype=np.int8))))
    if len(result):
        return np.vstack(result)
    return np.array([])

In [5]:
%%time
bounded_compositions_gray(8, [4, 3, 2, 1, 0])

CPU times: user 1.38 ms, sys: 0 ns, total: 1.38 ms
Wall time: 1.85 ms


array([[4, 3, 1, 0, 0],
       [4, 2, 2, 0, 0],
       [3, 3, 2, 0, 0],
       [2, 3, 2, 1, 0],
       [3, 2, 2, 1, 0],
       [4, 1, 2, 1, 0],
       [4, 2, 1, 1, 0],
       [3, 3, 1, 1, 0],
       [4, 3, 0, 1, 0]], dtype=int8)

In [6]:
class BoundedCompostionStorage:
    def __init__(self, n_max, s_max: int):
        '''
        0 <= s_max, n_max < 128
        '''
        self.n_max = n_max
        self.s_max = s_max
        self._map = dict()
        for n in range(n_max + 1):
            for s in range(n, n_max + 1):
                self._map[(n, s)] = np.array([n], dtype=np.int8)[:, None]
    
    def __call__(self, n, bounds):
        # print(f"inside BCS: n = {n}, bounds = {bounds}")
        s = len(bounds)
        if n > sum(bounds):
            return np.array([])
        
        key = tuple([n,] + bounds)
        if key in self._map:
            return self._map[key]
        
        result = []
        for k in range(bounds[-1] + 1):
            key = tuple([n - k,] + bounds[:-1])
            if key in self._map:
                prev = self._map[key]
            else:
                prev = bounded_compositions_gray(n - k, bounds[:-1])
                self._map[key] = np.copy(prev)
            if prev.shape[0]:
                if k % 2 == 1:
                    prev = prev[::-1]
                if len(prev) > 0:
                    result.append(np.hstack((prev, k * np.ones((prev.shape[0], 1), dtype=np.int8))))
        if len(result):
            self._map[tuple([n,] + bounds)] = np.vstack(result)
            return np.vstack(result)
        return np.array([])
    
    def __len__(self):
        return len(self._map)
    
    def count_contingency_matrices(self, r, c: np.array):
        assert np.sum(r) == np.sum(c), "row and column sums must be equal"
        if len(r) == 1:
            return 1
        result = 0
        n = len(c)
        for row in self(r[-1], c):
            result += count_contingency_matrices(r[:-1], c - row)
        return result

def test_bcs(n_max, s_max, atts=10, seed=42):
    bcs = BoundedCompostionStorage(n_max, s_max)
    # print(bcs._map.keys())
    np.random.seed(seed)
    for n in range(1, n_max + 1):
        # print(f"start of iteration {n}...")
        for s in range(1, s_max + 1):
            # print(f" s = {s}")
            for _ in range(atts):
                bounds = list(np.random.randint(0, n_max, size=(s,)))
                # print(f"  bounds = {bounds}, key = {tuple([n,] + bounds)}")
                cnt = count_bounded_compositions(n, bounds)
                combs = bcs(n, bounds)
                if cnt != combs.shape[0]:
                    print(n, bounds, cnt, combs)
        print(f"finish of iteration {n}, size of map = {len(bcs)}")

In [7]:
class ContingencyMatrixStorage:
    def __init__(self, max_r, n: int):
        self.bcs = BoundedCompostionStorage(max_r, n)
        self._map = dict()
    
    def __call__(self, rows, cols):
        assert np.sum(rows) == np.sum(cols), "row and column sums must be equal"
        if rows.shape[0] == 1:
            return cols
        
        key = (tuple(rows), tuple(cols))
        if key in self._map:
            return self._map[key]
        
        if rows.shape[0] == 2:
            matrix = []
            for row in self.bcs(rows[1], list(cols)):
                prev = self.bcs(rows[0], list(cols - row))
                N = prev.shape[0]
                if N:
                    matrix.append(
                        np.transpose(np.dstack((prev, np.tile(row, N).reshape(N, -1))), axes=(0, 2, 1))
                    )
            if len(matrix): 
                self._map[key] = np.vstack(matrix)
                return self._map[key]
            return np.array([])
        
        result = []
        for row in self.bcs(rows[-1], list(cols)):
            # print(f"rows = {rows}, cols = {cols}, row = {row}")
            prev = self(np.copy(rows[:-1]), cols - row)
            N = prev.shape[0]
            if N:
                # print(row, prev.shape)
                row_tiled = np.tile(row, N).reshape(N, -1)
                result.append(np.transpose(np.dstack((np.transpose(prev, axes=(0, 2, 1)), row_tiled)), axes=(0, 2, 1)))
        if len(result):
            self._map[key] = np.vstack(result)
            return self._map[key]
        return np.array([])
    
    def __len__(self):
        return len(self._map)

In [8]:
bcs = BoundedCompostionStorage(8, 4)
bcs(12, [8, 8, 8, 8]).shape

(375, 4)

In [10]:
%%time
cms = ContingencyMatrixStorage(8, 3)
rows = np.array([6, 8, 8, 8], dtype=np.int8)
cols = np.array([10, 10, 10], dtype=np.int8)
mats = cms(rows, cols)

CPU times: user 175 ms, sys: 4.63 ms, total: 180 ms
Wall time: 178 ms


In [11]:
mats.shape, len(cms)

((24303, 4, 3), 136)

In [12]:
unique, counts = np.unique(np.sum(np.abs(np.diff(mats, axis=0)), axis=(1, 2)), return_counts=True)
print(np.asarray((unique, counts)).T)

[[    4 22676]
 [    6    56]
 [    8    36]
 [   12    45]
 [   14   124]
 [   16    75]
 [   18   106]
 [   20   122]
 [   22   237]
 [   24   228]
 [   26   415]
 [   28   146]
 [   30     3]
 [   32     7]
 [   34    18]
 [   36     1]
 [   38     1]
 [   40     1]
 [   42     2]
 [   44     3]]


In [170]:
%%time
rows = np.array([10, 9, 8, 9], dtype=np.int8)
cols = np.array([9, 9, 9, 9], dtype=np.int8)
mats = cms(rows, cols)
mats.shape, len(cms)

CPU times: user 2.3 s, sys: 0 ns, total: 2.3 s
Wall time: 2.29 s


((2230228, 4, 4), 2059)

In [171]:
getsizeof(cms._map)

73816

In [17]:
d = dict()
d[tuple(np.array([1, 2, 3]))] = 1
d.keys()

dict_keys([(1, 2, 3)])

In [130]:
mat = np.vstack(([1,2,3], [4, 5, 6], [7, 8, 9], [0, 1, 0]))
tiled = np.tile([10, 20, 30], 4).reshape(4, 3)
mat.shape, tiled.shape

((4, 3), (4, 3))

In [138]:
N = 5
m = 4
n = 2
matrix = np.random.rand(N, m - 1, n)
matrix.shape

(5, 3, 2)

In [139]:
row = np.random.randint(1, 5, size=n)
row

array([2, 3])

In [144]:
row_tiled = np.tile(row, N).reshape(N, -1)
row_tiled.shape

(5, 2)

In [150]:
np.transpose(np.dstack((np.transpose(matrix, axes=(0, 2,1)), row_tiled)), axes=(0, 2, 1)).shape

(5, 4, 2)

In [131]:
d3 = np.transpose(np.dstack((mat, tiled)), axes=(0, 2, 1))
d3

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [10, 20, 30]],

       [[ 7,  8,  9],
        [10, 20, 30]],

       [[ 0,  1,  0],
        [10, 20, 30]]])

In [70]:
np.vstack((d3, d3))[-1]

array([[ 0,  1,  0],
       [10, 20, 30]])

In [219]:
%%time
bcs = BoundedCompostionStorage(8, 3)
bcs.count_contingency_matrices([7, 7, 8, 8], [10, 10, 10])

CPU times: user 406 ms, sys: 5 µs, total: 406 ms
Wall time: 404 ms


25191

In [216]:
%%time
bcs = BoundedCompostionStorage(10, 4)
bcs.count_contingency_matrices([10, 10, 10, 10], [10, 10, 10, 10])

CPU times: user 1min 6s, sys: 0 ns, total: 1min 6s
Wall time: 1min 6s


5045326

In [217]:
len(bcs)

78

In [165]:
%%time
test_bcs(32, 4, atts=20)

finish of iteration 1, size of map = 1575
finish of iteration 2, size of map = 2447
finish of iteration 3, size of map = 3234
finish of iteration 4, size of map = 4050
finish of iteration 5, size of map = 4766
finish of iteration 6, size of map = 5560
finish of iteration 7, size of map = 6299
finish of iteration 8, size of map = 6865
finish of iteration 9, size of map = 7569
finish of iteration 10, size of map = 8238
finish of iteration 11, size of map = 8965
finish of iteration 12, size of map = 9635
finish of iteration 13, size of map = 10313
finish of iteration 14, size of map = 10957
finish of iteration 15, size of map = 11640
finish of iteration 16, size of map = 12238
finish of iteration 17, size of map = 12737
finish of iteration 18, size of map = 13565
finish of iteration 19, size of map = 14290
finish of iteration 20, size of map = 15018
finish of iteration 21, size of map = 15637
finish of iteration 22, size of map = 16307
finish of iteration 23, size of map = 16957
finish of

In [8]:
def count_tables(suit_sizes, tables):
    equal_suits_trump = []
    for i in range(1, tables.shape[1] - 1):
        if suit_sizes[i] == suit_sizes[i + 1]:
            equal_suits_trump.append(i)
    no_trump, trump = tables.shape[0], tables.shape[0]
    deals_nt, deals_tr = 0, 0
    for i in range(tables.shape[0]):
        flag = False
        n_deals = 1
        for j in range(tables.shape[1]):
            n_deals *= int(multinomial(tables[i, j].astype(np.int64)))
        deals_nt += n_deals
        deals_tr += n_deals
        for j in equal_suits_trump:
            if not check_lex_order_for(tables[i][j], tables[i][j + 1]):
                trump -= 1
                no_trump -= 1
                deals_nt -= n_deals
                deals_tr -= n_deals
                flag = True
                break
        if not flag and suit_sizes[0] == suit_sizes[1] and not check_lex_order_for(tables[i, 0], tables[i, 1]):
            no_trump -= 1
            deals_nt -= n_deals
    return no_trump, deals_nt, trump, deals_tr
        

def list_suit_sizes(n_hands, max_hand_size, max_suit_size, min_hand_size=1):
    bcs = BoundedCompostionStorage(n_hands*max_hand_size, 4)
    cms = ContingencyMatrixStorage(max_suit_size, n_hands)
    print("{:^6} | {:^7} | {:^6} | {:^9} | {:^15} | {:^8} | {:^9} | {:^15}".format(
        "h_size", "s_sizes", "ss_nt", "tables_nt", "total_nt", "ss_trump", "tables_tr", "total_tr"
    ))
    total_trump, total_notrump, total_ss, total_deals_nt, total_deals_tr = 0, 0, 0, 0, 0
    total_tables, total_nt_tables, total_trump_tables = 0, 0, 0
    for hand_size in range(min_hand_size, max_hand_size + 1):
        suit_sizes = bcs(n_hands*hand_size, 4*[max_suit_size,])
        total_ss += suit_sizes.shape[0]
        notrump, trump = 0, 0
        n_tables, n_tables_nt, n_tables_trump = 0, 0, 0
        deals_notrump, deals_trump = 0, 0
        for suit_size in suit_sizes:
            # tables = cms(suit_size, hand_size * np.ones(n_hands, dtype=np.int8))
            # n_tables += tables.shape[0]
            if (suit_size[0] > 0 and is_sorted(suit_size[1:])) or is_sorted(suit_size):
                tables = cms(suit_size, hand_size * np.ones(n_hands, dtype=np.int8))
                tables_nt, deals_nt, tables_trump, deals_tr = count_tables(suit_size, tables)
                if suit_size[0] <= suit_size[1]:
                    notrump += 1
                    n_tables_nt += tables_nt
                    deals_notrump += deals_nt
                if suit_size[0]:
                    trump += 1
                    n_tables_trump += tables_trump
                    deals_trump += deals_tr
        total_trump += trump
        total_notrump += notrump
        total_tables += n_tables
        total_nt_tables += n_tables_nt
        total_trump_tables += n_tables_trump
        total_deals_nt += deals_notrump
        total_deals_tr += deals_trump
        print("{:^6} | {:^7} | {:^6} | {:^9} | {:^15.9e} | {:^8} | {:^9} | {:^15.9e}".format(
            hand_size, suit_sizes.shape[0], notrump, n_tables_nt, deals_notrump, trump, n_tables_trump, deals_trump
        ))
    print("Total suit sizes distributions:", total_ss)
    print("NT suit sizes distributions:", total_notrump)
    print("Trump suit sizes distributions:", total_trump)
    print("Total contingency tables:", total_tables)
    print("Total NT contingency tables:", total_nt_tables)
    print("Total trump contingency tables:", total_trump_tables)
    print("Total NT deals:", total_deals_nt)
    print("Total trump deals:", total_deals_tr)
    print(len(bcs), len(cms))

In [9]:
%%time
list_suit_sizes(3, 10, 8)

h_size | s_sizes | ss_nt  | tables_nt |    total_nt     | ss_trump | tables_tr |    total_tr    
  1    |   20    |   3    |     5     | 1.300000000e+01 |    4     |    10     | 2.100000000e+01
  2    |   84    |   9    |    59     | 5.550000000e+02 |    16    |    159    | 1.188000000e+03
  3    |   216   |   17   |    389    | 1.999600000e+04 |    40    |   1272    | 5.506200000e+04
  4    |   375   |   27   |   1921    | 6.319590000e+05 |    69    |   6801    | 1.974972000e+06
  5    |   480   |   31   |   6806    | 1.635001200e+07 |    90    |   25509   | 5.632142400e+07
  6    |   456   |   31   |   17825   | 3.417186840e+08 |    90    |   68760   | 1.251390792e+09
  7    |   324   |   23   |   33053   | 5.611979988e+09 |    69    |  129969   | 2.131163650e+10
  8    |   165   |   15   |   41650   | 6.856570220e+10 |    40    |  164893   | 2.652350614e+11
  9    |   56    |   6    |   31428   | 5.676037936e+11 |    16    |  124563   | 2.198253354e+12
  10   |   10    |   2    |   

In [43]:
143837 + 564020

707857

In [28]:
%%time
list_suit_sizes(4, 13, 13)

h_size | s_sizes | ss_nt  | tables_nt |    total_nt     | ss_trump | tables_tr |    total_tr    
  1    |   35    |   5    |    15     | 7.300000000e+01 |    7     |    37     | 1.360000000e+02
  2    |   165   |   15   |    483    | 2.508900000e+04 |    31    |   1571    | 6.283200000e+04
  3    |   455   |   34   |   6996    | 8.631656000e+06 |    83    |   25645   | 2.528905600e+07
  4    |   929   |   60   |   64157   | 2.695695469e+09 |   167    |  244857   | 8.838244832e+09
  5    |  1435   |   85   |  411559   | 7.355502747e+11 |   257    |  1605556  | 2.586025683e+12
  6    |  1781   |  102   |  1987370  | 1.752645429e+14 |   322    |  7840071  | 6.440266019e+14
  7    |  1781   |  102   |  7325169  | 3.532338807e+16 |   331    | 29098695  | 1.346213175e+17
  8    |  1435   |   85   | 20544831  | 5.983993546e+18 |   277    | 81916548  | 2.327423195e+19
  9    |   929   |   60   | 42792548  | 8.345836406e+20 |   190    | 170964452 | 3.294018749e+21
  10   |   455   |   34   | 63

/usr/local/lib/python3.9/dist-packages/numpy/core/_methods.py:52: RuntimeWarning: overflow encountered in reduce
  return umr_prod(a, axis, dtype, out, keepdims, initial, where)
/tmp/ipykernel_21040/301531815.py:11: RuntimeWarning: invalid value encountered in float_scalars
  n_deals = int(suit_size_fact / factorial(tables[i]).prod())


ValueError: cannot convert float NaN to integer

In [10]:
%%time
list_suit_sizes(4, 13, 13, 13)

h_size | s_sizes | ss_nt  | tables_nt |    total_nt     | ss_trump | tables_tr |    total_tr    
  13   |    1    |   1    |  1569344  | 2.330485140e+27 |    1     |  6261900  | 9.130173365e+27
Total suit sizes distributions: 1
NT suit sizes distributions: 1
Trump suit sizes distributions: 1
Total contingency tables: 0
Total NT contingency tables: 1569344
Total trump contingency tables: 6261900
Total NT deals: 2330485140043048865633870400
Total trump deals: 9130173364854237384896860800
1446 2395
CPU times: user 24min 19s, sys: 25.2 s, total: 24min 44s
Wall time: 24min 12s


In [11]:
2330485140043048865633870400 + 3.479219452e+26  + 7.252090606e+24 + 8.973169035e+22 + 8.345836406e+20 + 5.983993546e+18

2.6857497481070334e+27

In [13]:
9130173364854237384896860800 + 1.383511706e+27 + 2.890133254e+25 + 3.578666684e+23 + 3.294018749e+21 + 2.327423195e+19

1.0542947587355617e+28

In [200]:
%%time
list_suit_sizes(4, 13, 13)

  size   | unordered | no trump |  trump  
   1     |    35     |    5     |    7    
   2     |    165    |    15    |    31   
   3     |    455    |    34    |    83   
   4     |    929    |    60    |   167   
   5     |   1435    |    85    |   257   
   6     |   1781    |   102    |   322   
   7     |   1781    |   102    |   331   
   8     |   1435    |    85    |   277   
   9     |    929    |    60    |   190   
   10    |    455    |    34    |   102   
   11    |    165    |    15    |    41   
   12    |    35     |    5     |    11   
   13    |     1     |    1     |    1    
603 1820
1506
CPU times: user 123 ms, sys: 16 ms, total: 139 ms
Wall time: 123 ms


In [160]:
%%time
bcs(5, [8, 3, 4, 5])

CPU times: user 10 µs, sys: 0 ns, total: 10 µs
Wall time: 14.1 µs


array([[5, 0, 0, 0],
       [4, 1, 0, 0],
       [3, 2, 0, 0],
       [2, 3, 0, 0],
       [1, 3, 1, 0],
       [2, 2, 1, 0],
       [3, 1, 1, 0],
       [4, 0, 1, 0],
       [3, 0, 2, 0],
       [2, 1, 2, 0],
       [1, 2, 2, 0],
       [0, 3, 2, 0],
       [0, 2, 3, 0],
       [1, 1, 3, 0],
       [2, 0, 3, 0],
       [1, 0, 4, 0],
       [0, 1, 4, 0],
       [0, 0, 4, 1],
       [1, 0, 3, 1],
       [0, 1, 3, 1],
       [0, 2, 2, 1],
       [1, 1, 2, 1],
       [2, 0, 2, 1],
       [3, 0, 1, 1],
       [2, 1, 1, 1],
       [1, 2, 1, 1],
       [0, 3, 1, 1],
       [1, 3, 0, 1],
       [2, 2, 0, 1],
       [3, 1, 0, 1],
       [4, 0, 0, 1],
       [3, 0, 0, 2],
       [2, 1, 0, 2],
       [1, 2, 0, 2],
       [0, 3, 0, 2],
       [0, 2, 1, 2],
       [1, 1, 1, 2],
       [2, 0, 1, 2],
       [1, 0, 2, 2],
       [0, 1, 2, 2],
       [0, 0, 3, 2],
       [0, 0, 2, 3],
       [1, 0, 1, 3],
       [0, 1, 1, 3],
       [0, 2, 0, 3],
       [1, 1, 0, 3],
       [2, 0, 0, 3],
       [1, 0,

In [6]:
def count_ordered_bounded_compositions(n, s, b):
    d = np.zeros((n + 1, b + 1, s + 1), dtype=np.int32)
    d[:, :, 0] = 0
    d[0, :, 0] = 1
    for k in range(1, s + 1):
        d[:, 0, k] = 0
        d[0, :, k] = 1
        for j in range(1, n + 1):
            for m in range(1, b + 1):
                idx = np.arange(min(j, m) + 1)
                d[j, m, k] = d[j - idx, idx, k - 1].sum()
    return int(d[n, b, s])
    # return d

In [7]:
%%time
count_ordered_bounded_compositions(18, 4, 8)

CPU times: user 9.59 ms, sys: 6.26 ms, total: 15.9 ms
Wall time: 10.2 ms


31

In [22]:
for n in range(1, 20):
    for s in range(1, 10):
        for _ in range(10):
            bounds = np.random.randint(0, 10, size=s)
            if count_bounded_compositions(n, bounds) != count_bounded_compositions_visiting(n, bounds):
                print(n, bounds)

In [27]:
for n in range(1, 20):
    for s in range(1, 10):
        for b in range(5):
            if count_ordered_bounded_compositions(n, s, b) != count_bounded_compositions_visiting(n, s*[b,], True):
                print(n, bounds)

In [24]:
%%time
count_bounded_compositions_visiting(26, [13, 13, 13, 13])

CPU times: user 37.5 ms, sys: 16 ms, total: 53.5 ms
Wall time: 46.3 ms


1834

In [25]:
%%time
count_bounded_compositions(26, [13, 13, 13, 13])

CPU times: user 120 µs, sys: 0 ns, total: 120 µs
Wall time: 125 µs


1834

In [28]:
def count_trump_deals(n_hands, hand_size, max_suit_size):
    result = 0
    for trump_size in range(1, min(max_suit_size, n_hands*hand_size) + 1):
        result += count_ordered_bounded_compositions(n_hands*hand_size - trump_size, 3, max_suit_size)
    return result

def count_stage_deals(n_hands, max_hand_size, max_suit_size, ordered=True):
    total_suit_sizes = 0
    total_suit_sizes_trump = 0
    total_deals = 0
    total_deals_trump = 0
    for hand_size in range(1, max_hand_size + 1):
        if ordered:
            suit_sizes = count_ordered_bounded_compositions(n_hands * hand_size, 4, max_suit_size)
            suit_sizes_trump = count_trump_deals(n_hands, hand_size, max_suit_size)
            total_suit_sizes_trump += suit_sizes_trump
        else:
            suit_sizes = count_bounded_compositions(n_hands * hand_size, 4 * [max_suit_size,])
        n_deals = suit_sizes * multinomial(n_hands * [hand_size,])
        summary = f"hand_size = {hand_size}, #suit_sizes = {suit_sizes}, n_deals = {n_deals}"
        if ordered:
            n_deals_trump = suit_sizes_trump * multinomial(n_hands * [hand_size,])
            total_deals_trump += n_deals_trump
            summary += f", suit_sizes_trump = {suit_sizes_trump}, n_deals_trump = {n_deals_trump}"
        total_suit_sizes += suit_sizes
        total_deals += n_deals
        print(summary)
    print("Total suit sizes:", total_suit_sizes)
    print("Total deals: {:e}".format(total_deals))
    if ordered:
        print("Total suit sizes trump:", total_suit_sizes_trump)
        print("Total deals trump: {:e}".format(total_deals_trump))

In [29]:
count_stage_deals(3, 10, 8, False)

hand_size = 1, #suit_sizes = 20, n_deals = 120
hand_size = 2, #suit_sizes = 84, n_deals = 7560
hand_size = 3, #suit_sizes = 216, n_deals = 362880
hand_size = 4, #suit_sizes = 375, n_deals = 12993750
hand_size = 5, #suit_sizes = 480, n_deals = 363242880
hand_size = 6, #suit_sizes = 456, n_deals = 7821830016
hand_size = 7, #suit_sizes = 324, n_deals = 129299639040
hand_size = 8, #suit_sizes = 165, n_deals = 1561809442050
hand_size = 9, #suit_sizes = 56, n_deals = 12760912164000
hand_size = 10, #suit_sizes = 10, n_deals = 55509967913400
Total suit sizes: 2186
Total deals: 6.997019e+13


In [30]:
count_stage_deals(3, 10, 8, True)

hand_size = 1, #suit_sizes = 3, n_deals = 18, suit_sizes_trump = 4, n_deals_trump = 24
hand_size = 2, #suit_sizes = 9, n_deals = 810, suit_sizes_trump = 16, n_deals_trump = 1440
hand_size = 3, #suit_sizes = 17, n_deals = 28560, suit_sizes_trump = 40, n_deals_trump = 67200
hand_size = 4, #suit_sizes = 27, n_deals = 935550, suit_sizes_trump = 69, n_deals_trump = 2390850
hand_size = 5, #suit_sizes = 31, n_deals = 23459436, suit_sizes_trump = 90, n_deals_trump = 68108040
hand_size = 6, #suit_sizes = 31, n_deals = 531747216, suit_sizes_trump = 90, n_deals_trump = 1543782240
hand_size = 7, #suit_sizes = 23, n_deals = 9178678080, suit_sizes_trump = 69, n_deals_trump = 27536034240
hand_size = 8, #suit_sizes = 15, n_deals = 141982676550, suit_sizes_trump = 40, n_deals_trump = 378620470800
hand_size = 9, #suit_sizes = 6, n_deals = 1367240589000, suit_sizes_trump = 16, n_deals_trump = 3645974904000
hand_size = 10, #suit_sizes = 2, n_deals = 11101993582680, suit_sizes_trump = 4, n_deals_trump = 22

In [31]:
count_stage_deals(4, 8, 8, False)

hand_size = 1, #suit_sizes = 35, n_deals = 840
hand_size = 2, #suit_sizes = 165, n_deals = 415800
hand_size = 3, #suit_sizes = 375, n_deals = 138600000
hand_size = 4, #suit_sizes = 489, n_deals = 30837807000
hand_size = 5, #suit_sizes = 375, n_deals = 4399779384000
hand_size = 6, #suit_sizes = 165, n_deals = 380942676354240
hand_size = 7, #suit_sizes = 35, n_deals = 16538142164544000
hand_size = 8, #suit_sizes = 1, n_deals = 99561092450391000
Total suit sizes: 1640
Total deals: 1.164846e+17


In [32]:
count_stage_deals(4, 8, 8, True)

hand_size = 1, #suit_sizes = 5, n_deals = 120, suit_sizes_trump = 7, n_deals_trump = 168
hand_size = 2, #suit_sizes = 15, n_deals = 37800, suit_sizes_trump = 31, n_deals_trump = 78120
hand_size = 3, #suit_sizes = 27, n_deals = 9979200, suit_sizes_trump = 69, n_deals_trump = 25502400
hand_size = 4, #suit_sizes = 33, n_deals = 2081079000, suit_sizes_trump = 93, n_deals_trump = 5864859000
hand_size = 5, #suit_sizes = 27, n_deals = 316784115648, suit_sizes_trump = 78, n_deals_trump = 915154111872
hand_size = 6, #suit_sizes = 15, n_deals = 34631152395840, suit_sizes_trump = 40, n_deals_trump = 92349739722240
hand_size = 7, #suit_sizes = 5, n_deals = 2362591737792000, suit_sizes_trump = 11, n_deals_trump = 5197701823142400
hand_size = 8, #suit_sizes = 1, n_deals = 99561092450391000, suit_sizes_trump = 1, n_deals_trump = 99561092450391000
Total suit sizes: 128
Total deals: 1.019586e+17
Total suit sizes trump: 330
Total deals trump: 1.048521e+17


In [33]:
count_stage_deals(4, 13, 13, False)

hand_size = 1, #suit_sizes = 35, n_deals = 840
hand_size = 2, #suit_sizes = 165, n_deals = 415800
hand_size = 3, #suit_sizes = 455, n_deals = 168168000
hand_size = 4, #suit_sizes = 929, n_deals = 58585527000
hand_size = 5, #suit_sizes = 1435, n_deals = 16836489109440
hand_size = 6, #suit_sizes = 1781, n_deals = 4111872161132736
hand_size = 7, #suit_sizes = 1781, n_deals = 841555177001510400
hand_size = 8, #suit_sizes = 1435, n_deals = 142870167666311085000
hand_size = 9, #suit_sizes = 929, n_deals = 19929606855360482280000
hand_size = 10, #suit_sizes = 455, n_deals = 2140939196338474453521600
hand_size = 11, #suit_sizes = 165, n_deals = 172766851765048056727411200
hand_size = 12, #suit_sizes = 35, n_deals = 8253325551174991447325256000
hand_size = 13, #suit_sizes = 1, n_deals = 53644737765488792839237440000
Total suit sizes: 9601
Total deals: 6.207299e+28


In [34]:
count_stage_deals(4, 13, 13, True)

hand_size = 1, #suit_sizes = 5, n_deals = 120, suit_sizes_trump = 7, n_deals_trump = 168
hand_size = 2, #suit_sizes = 15, n_deals = 37800, suit_sizes_trump = 31, n_deals_trump = 78120
hand_size = 3, #suit_sizes = 34, n_deals = 12566400, suit_sizes_trump = 83, n_deals_trump = 30676800
hand_size = 4, #suit_sizes = 60, n_deals = 3783780000, suit_sizes_trump = 167, n_deals_trump = 10531521000
hand_size = 5, #suit_sizes = 85, n_deals = 997283327040, suit_sizes_trump = 257, n_deals_trump = 3015315471168
hand_size = 6, #suit_sizes = 102, n_deals = 235491836291712, suit_sizes_trump = 322, n_deals_trump = 743415404764032
hand_size = 7, #suit_sizes = 102, n_deals = 48196871450956800, suit_sizes_trump = 331, n_deals_trump = 156403573041830400
hand_size = 8, #suit_sizes = 85, n_deals = 8462692858283235000, suit_sizes_trump = 277, n_deals_trump = 27578422608758307000
hand_size = 9, #suit_sizes = 60, n_deals = 1287165135975919200000, suit_sizes_trump = 190, n_deals_trump = 4076022930590410800000
han

In [45]:
%%time
r = np.array([8, 8, 8, 8])
c = np.array([10, 10, 10, 2])
count_contingency_matrices(r, c)

CPU times: user 2.92 s, sys: 0 ns, total: 2.92 s
Wall time: 2.92 s


248358

In [2]:
for q in bounded_compositions(5, 4, [4, 3, 2, 1]):
    print(q)

[4 1 0 0]
[3 2 0 0]
[2 3 0 0]
[4 0 1 0]
[3 1 1 0]
[2 2 1 0]
[1 3 1 0]
[3 0 2 0]
[2 1 2 0]
[1 2 2 0]
[0 3 2 0]
[4 0 0 1]
[3 1 0 1]
[2 2 0 1]
[1 3 0 1]
[3 0 1 1]
[2 1 1 1]
[1 2 1 1]
[0 3 1 1]
[2 0 2 1]
[1 1 2 1]
[0 2 2 1]


In [27]:
count_bounded_compositions(5, [4, 3, 2, 1])

22

In [46]:
%%time
for c in compositions(5, 4):
    print(c)

[5 0 0 0]
[4 1 0 0]
[3 2 0 0]
[2 3 0 0]
[1 4 0 0]
[0 5 0 0]
[4 0 1 0]
[3 1 1 0]
[2 2 1 0]
[1 3 1 0]
[0 4 1 0]
[3 0 2 0]
[2 1 2 0]
[1 2 2 0]
[0 3 2 0]
[2 0 3 0]
[1 1 3 0]
[0 2 3 0]
[1 0 4 0]
[0 1 4 0]
[0 0 5 0]
[4 0 0 1]
[3 1 0 1]
[2 2 0 1]
[1 3 0 1]
[0 4 0 1]
[3 0 1 1]
[2 1 1 1]
[1 2 1 1]
[0 3 1 1]
[2 0 2 1]
[1 1 2 1]
[0 2 2 1]
[1 0 3 1]
[0 1 3 1]
[0 0 4 1]
[3 0 0 2]
[2 1 0 2]
[1 2 0 2]
[0 3 0 2]
[2 0 1 2]
[1 1 1 2]
[0 2 1 2]
[1 0 2 2]
[0 1 2 2]
[0 0 3 2]
[2 0 0 3]
[1 1 0 3]
[0 2 0 3]
[1 0 1 3]
[0 1 1 3]
[0 0 2 3]
[1 0 0 4]
[0 1 0 4]
[0 0 1 4]
[0 0 0 5]
CPU times: user 5.97 ms, sys: 9 µs, total: 5.98 ms
Wall time: 5.34 ms


In [27]:
is_sorted = lambda a: np.all(a[:-1] <= a[1:])

def is_sorted_for(a: np.array):
    for i in range(a.shape[0] - 1):
        if a[i] > a[i + 1]:
            return False
    return True

In [28]:
%%timeit
np.random.seed(66)
is_sorted(np.random.randint(8, size=4))

19.1 µs ± 631 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [29]:
%%timeit
np.random.seed(66)
is_sorted_for(np.random.randint(8, size=4))

11.1 µs ± 214 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
s = 0
for n_suits in range(1, 5):
    s += get_suit_sizes(n_suits).shape[0]
print(s)

438


In [10]:
all_hashes = set()

def add_matrix_hashes(matrices):
    for matrix in tqdm(matrices):
        if len(matrix.shape) < 2:
            pct = PrefContingencyTable(matrix, False)
            all_hashes.add(hash(pct))
        else:
            pct = PrefContingencyTable(matrix, True)
            all_hashes.add(hash(pct))
            suit_sizes = np.sum(matrix, axis=1)
            if suit_sizes[0] <= suit_sizes[1]:
                pct = PrefContingencyTable(matrix, False)
                all_hashes.add(hash(pct))
                matrices_by_hand_size[h]
add_matrix_hashes(mat1)
add_matrix_hashes(mat2)
add_matrix_hashes(mat3)
add_matrix_hashes(mat4)
print(len(all_hashes))

  1%|▌                                        | 3/232 [00:00<00:00, 9739.10it/s]


NameError: name 'matrices_by_hand_size' is not defined

In [38]:
type(mat4[8907].tolist()[0][0])

int

In [24]:
from collections import defaultdict

def matrix_hashes_by_hand_size(matrices_list):
    result = defaultdict(list)
    for matrices in matrices_list:
        for matrix in tqdm(matrices):
            hand_size = matrix.sum() // 3
            if len(matrix.shape) < 2:
                pct = PrefContingencyTable(matrix, False)
                result[hand_size].append(hash(pct))
            else:
                pct = PrefContingencyTable(matrix, True)
                result[hand_size].append(hash(pct))
                suit_sizes = np.sum(matrix, axis=1)
                if suit_sizes[0] < suit_sizes[1] or \
                (suit_sizes[0] == suit_sizes[1] and check_lex_order_for(matrix[0], matrix[1])):
                    pct = PrefContingencyTable(matrix, False)
                    result[hand_size].append(hash(pct))
    return result

In [25]:
matrices_by_hand_size = matrix_hashes_by_hand_size([mat1, mat2, mat3, mat4])

100%|████████████████████████████████| 550727/550727 [00:15<00:00, 35893.83it/s]


In [26]:
total = 0
for h in range(1, 11):
    print(len(matrices_by_hand_size[h]))
    total += len(matrices_by_hand_size[h])
print(total)

14
217
1661
8722
32315
86585
163022
206543
155991
52785
707855


In [29]:
matrices_by_hand_size[2]

[86,
 18507,
 10315,
 17483,
 18619,
 10427,
 17595,
 2235,
 9403,
 16571,
 10539,
 17707,
 2347,
 9515,
 9514,
 16683,
 16682,
 1323,
 1322,
 8491,
 8490,
 2459,
 2458,
 9627,
 9626,
 16795,
 16794,
 1435,
 1434,
 8603,
 8602,
 411,
 410,
 1547,
 1546,
 8715,
 8714,
 523,
 522,
 147519,
 81983,
 139327,
 4210751,
 4268095,
 655423,
 4277295,
 82991,
 664623,
 140335,
 4211759,
 17455,
 599087,
 4269103,
 74799,
 656431,
 132143,
 533551,
 4203567,
 590895,
 4260911,
 4211871,
 17567,
 4269215,
 74911,
 656543,
 656542,
 132255,
 8397983,
 4203679,
 591007,
 591006,
 4261023,
 4261022,
 4719775,
 4719774,
 8389791,
 8389790,
 4212767,
 18463,
 600095,
 4270111,
 75807,
 657439,
 133151,
 534559,
 4204575,
 10271,
 591903,
 4261919,
 67615,
 526367,
 4196383,
 4728975,
 4728974,
 8398991,
 8398990,
 534671,
 534670,
 4204687,
 4204686,
 10383,
 10382,
 1116303,
 1116302,
 4786319,
 4786318,
 592015,
 592014,
 4262031,
 4262030,
 67727,
 67726,
 1050767,
 1050766,
 4720783,
 4720782,
 83

In [14]:
max_hash = 0
for h in all_hashes:
    if h > max_hash:
        max_hash = h
max_hash

3907043276

In [36]:
pct = PrefContingencyTable(mat4[234289], True)

In [37]:
print("{:b}".format(hash(pct)))

10000000101001110011010001111101


In [38]:
print(f"{hash(pct)}")

2158441597


In [17]:
0b11

3

In [40]:
pct_from_hash = PrefContingencyTable.from_hash(2158441597)
pct_from_hash

♠ 431
♣ 211
♦ 041
♥ 205

In [11]:
pct_from_hash.matrix

array([[ 1,  0,  2],
       [ 0,  2,  4],
       [ 4,  3, -1]], dtype=int8)

In [14]:
from sympy.utilities.iterables import multiset_permutations

for perm in multiset_permutations([0, 0, 1, 2]):
    print(perm)

[0, 0, 1, 2]
[0, 0, 2, 1]
[0, 1, 0, 2]
[0, 1, 2, 0]
[0, 2, 0, 1]
[0, 2, 1, 0]
[1, 0, 0, 2]
[1, 0, 2, 0]
[1, 2, 0, 0]
[2, 0, 0, 1]
[2, 0, 1, 0]
[2, 1, 0, 0]


In [95]:
def perm2suit(perm):
    result = []
    for i, hand_index in enumerate(perm):
        while len(result) < hand_index + 1:
            result.append([])
        result[hand_index].append(i)
    return result

class TrickCounter:
    def __init__(self, n_hands=3, reduce=True):
        self.trick = []
        self.reduce = reduce
        self.result = np.zeros(n_hands, dtype=np.int32)
        
    def __call__(self, suit):
        for i, card in enumerate(suit[0]):
            if self.reduce and i + 1 < len(suit[0]) and card + 1 == suit[0][i + 1]:
                continue
            self.trick.append(card)
            if len(suit) > 1:
                self(suit[1:])
            else:
                self.result[np.argmax(self.trick)] += 1
            self.trick.pop()
            
    def count(self):
        return self.result
            
            
def count_takers(suit_sizes: np.array, reduce=True):
    hand_list = []
    for i in range(len(suit_sizes)):
        hand_list.extend(suit_sizes[i] * [i,])
    
    suit_map = {}
        
    def trick_counter(suit, reduce=reduce):
        nonlocal trick, count, suit_map
        key = sorted(tuple(suit))
        if key in suit_map:
            count = suit_map[key]
            return
        for i, card in enumerate(suit[0]):
            if reduce and i + 1 < len(suit[0]) and card + 1 == suit[0][i + 1]:
                continue
            trick.append(card)
            if len(suit) > 1:
                trick_counter(suit[1:], reduce)
            else:
                if np.argmax(trick) == 0:
                    count += 1
            trick.pop()
        suit_map[key] = suit
    
    total = 0
    for perm in multiset_permutations(hand_list):
        suit = perm2suit(perm)
        trick = []
        count = 0
        trick_counter(suit)
        total += count
    return total

In [ ]:
def adjacent_matrices(hand_size):
    graph = []
    with psycopg2.connect('postgres://rafael:VfPLiCASXsMd7Y@localhost/preferance') as conn:
        with conn.cursor() as cur:
            query = f'''
                SELECT hash, matrix::int[][] FROM contingency_tables WHERE hand_size = {hand_size}
            '''
            cur.execute(query)
            for record in cur:
                hash_code = int(record[0].hex(), base=16)
                trump = hash_code & 1 == 1
                matrix = np.array(record[1], dtype=np.int8)
                pct = PrefContingencyTable(matrix, trump)
                for i in range(matrix.shape[0]):
                    if np.min(matrix[i]) > 0:
                    

In [99]:
%%time
count_takers(np.array([4, 3], dtype=int), reduce=True)

CPU times: user 0 ns, sys: 3.51 ms, total: 3.51 ms
Wall time: 2.78 ms


90

In [30]:
trick_counter = TrickCounter()
trick_counter([[0, 1], [2], [3]])
trick_counter.count()

array([0, 0, 2], dtype=int32)

In [27]:
trick_counter.result

array([0, 0, 2], dtype=int32)

In [71]:
for perm in multiset_permutations([0,0,1,2]):
    print(perm2suit(perm))

[[0, 1], [2], [3]]
[[0, 1], [3], [2]]
[[0, 2], [1], [3]]
[[0, 3], [1], [2]]
[[0, 2], [3], [1]]
[[0, 3], [2], [1]]
[[1, 2], [0], [3]]
[[1, 3], [0], [2]]
[[2, 3], [0], [1]]
[[1, 2], [3], [0]]
[[1, 3], [2], [0]]
[[2, 3], [1], [0]]


In [6]:
total = 0
for n in range(1, 9):
    for s in bounded_compositions(n, 2, [8, 8]):
        if min(s) > 0:
            total += 1
            print(s)
print(total)

[1 1]
[2 1]
[1 2]
[3 1]
[2 2]
[1 3]
[4 1]
[3 2]
[2 3]
[1 4]
[5 1]
[4 2]
[3 3]
[2 4]
[1 5]
[6 1]
[5 2]
[4 3]
[3 4]
[2 5]
[1 6]
[7 1]
[6 2]
[5 3]
[4 4]
[3 5]
[2 6]
[1 7]
28


In [5]:
total = 0
for n in range(1, 9):
    for s in bounded_compositions(n, 3, [8, 8, 8]):
        if min(s) > 0:
            total += 1
            print(s)
print(total)

[1 1 1]
[2 1 1]
[1 2 1]
[1 1 2]
[3 1 1]
[2 2 1]
[1 3 1]
[2 1 2]
[1 2 2]
[1 1 3]
[4 1 1]
[3 2 1]
[2 3 1]
[1 4 1]
[3 1 2]
[2 2 2]
[1 3 2]
[2 1 3]
[1 2 3]
[1 1 4]
[5 1 1]
[4 2 1]
[3 3 1]
[2 4 1]
[1 5 1]
[4 1 2]
[3 2 2]
[2 3 2]
[1 4 2]
[3 1 3]
[2 2 3]
[1 3 3]
[2 1 4]
[1 2 4]
[1 1 5]
[6 1 1]
[5 2 1]
[4 3 1]
[3 4 1]
[2 5 1]
[1 6 1]
[5 1 2]
[4 2 2]
[3 3 2]
[2 4 2]
[1 5 2]
[4 1 3]
[3 2 3]
[2 3 3]
[1 4 3]
[3 1 4]
[2 2 4]
[1 3 4]
[2 1 5]
[1 2 5]
[1 1 6]
56
