In [2]:
from perms import *
import numpy as np

In [3]:
invert_permutation([1, 2, 3, 0])

array([3, 0, 1, 2])

In [4]:
%%time
perm2index(np.array([3, 1, 4, 5, 9, 2, 6, 8, 7]) - 1)

CPU times: user 579 µs, sys: 1.07 ms, total: 1.65 ms
Wall time: 1.34 ms


81577

In [5]:
%%time
index2perm(81577, 9) + 1

CPU times: user 167 µs, sys: 0 ns, total: 167 µs
Wall time: 172 µs


array([3, 1, 4, 5, 9, 2, 6, 8, 7])

In [5]:
N = 4
for perm in get_all_perms(N, False):
    it = inversion_table(perm)[::-1]
    print("Perm:", perm)
    print("Inversion table:", it)
    print(factoradic2decimal(it))

Mean column values: [1.5 1.5 1.5 1.5]
Column std: [1.11803399 1.11803399 1.11803399 1.11803399]
Perm: [0 1 2 3]
Inversion table: [0 0 0 0]
0
Perm: [0 1 3 2]
Inversion table: [0 1 0 0]
1
Perm: [0 2 1 3]
Inversion table: [0 0 1 0]
2
Perm: [0 2 3 1]
Inversion table: [0 1 1 0]
3
Perm: [0 3 1 2]
Inversion table: [0 0 2 0]
4
Perm: [0 3 2 1]
Inversion table: [0 1 2 0]
5
Perm: [1 0 2 3]
Inversion table: [0 0 0 1]
6
Perm: [1 0 3 2]
Inversion table: [0 1 0 1]
7
Perm: [1 2 0 3]
Inversion table: [0 0 1 1]
8
Perm: [1 2 3 0]
Inversion table: [0 1 1 1]
9
Perm: [1 3 0 2]
Inversion table: [0 0 2 1]
10
Perm: [1 3 2 0]
Inversion table: [0 1 2 1]
11
Perm: [2 0 1 3]
Inversion table: [0 0 0 2]
12
Perm: [2 0 3 1]
Inversion table: [0 1 0 2]
13
Perm: [2 1 0 3]
Inversion table: [0 0 1 2]
14
Perm: [2 1 3 0]
Inversion table: [0 1 1 2]
15
Perm: [2 3 0 1]
Inversion table: [0 0 2 2]
16
Perm: [2 3 1 0]
Inversion table: [0 1 2 2]
17
Perm: [3 0 1 2]
Inversion table: [0 0 0 3]
18
Perm: [3 0 2 1]
Inversion table: [0 1 0 

In [16]:
N = 5000
np.random.seed(2312)
random_perm = np.arange(N)
np.random.shuffle(random_perm)
print(random_perm[:10])

[1637 2317 2858 2350  434 4759 1528 3662 2461  649]


In [18]:
%%time
it = inversion_table(random_perm)
it[-10:]

CPU times: user 158 ms, sys: 4.08 ms, total: 162 ms
Wall time: 161 ms


array([8, 5, 0, 3, 3, 4, 0, 2, 0, 0], dtype=int32)

In [2]:
%%time
p4 = get_all_perms(4, False)

Mean column values: [1.5 1.5 1.5 1.5]
Column std: [1.11803399 1.11803399 1.11803399 1.11803399]
CPU times: user 489 µs, sys: 1.01 ms, total: 1.5 ms
Wall time: 1.25 ms


In [4]:
%%time
p4_fast = get_all_perms(4, True)

Mean column values: [1.5 1.5 1.5 1.5]
Column std: [1.11803399 1.11803399 1.11803399 1.11803399]
CPU times: user 2.3 ms, sys: 0 ns, total: 2.3 ms
Wall time: 1.66 ms


In [5]:
%%time
p5 = get_all_perms(5, False)

Mean column values: [2. 2. 2. 2. 2.]
Column std: [1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]
CPU times: user 3.45 ms, sys: 0 ns, total: 3.45 ms
Wall time: 2.37 ms


In [6]:
%%time
p5_fast = get_all_perms(5, True)

Mean column values: [2. 2. 2. 2. 2.]
Column std: [1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]
CPU times: user 0 ns, sys: 4.3 ms, total: 4.3 ms
Wall time: 2.85 ms


In [4]:
%%time
p6 = get_all_perms(6)

Mean column values: [2.5 2.5 2.5 2.5 2.5 2.5]
Сolumn std: [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
CPU times: user 7.91 ms, sys: 0 ns, total: 7.91 ms
Wall time: 5.51 ms


In [10]:
%%time
p6_fast = get_all_perms(6, True)

Mean column values: [2.5 2.5 2.5 2.5 2.5 2.5]
Column std: [1.70782513 1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
CPU times: user 8.08 ms, sys: 0 ns, total: 8.08 ms
Wall time: 4.96 ms


In [14]:
%%time
p7 = get_all_perms(7, False)

Mean column values: [3. 3. 3. 3. 3. 3. 3.]
Column std: [2. 2. 2. 2. 2. 2. 2.]
CPU times: user 21.6 ms, sys: 2.28 ms, total: 23.8 ms
Wall time: 21 ms


In [15]:
%%time
p7_fast = get_all_perms(7, True)

Mean column values: [3. 3. 3. 3. 3. 3. 3.]
Column std: [2. 2. 2. 2. 2. 2. 2.]
CPU times: user 17.4 ms, sys: 0 ns, total: 17.4 ms
Wall time: 15.7 ms


In [18]:
%%time
p8 = get_all_perms(8, False)

Mean column values: [3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5]
Column std: [2.29128785 2.29128785 2.29128785 2.29128785 2.29128785 2.29128785
 2.29128785 2.29128785]
CPU times: user 118 ms, sys: 3.73 ms, total: 121 ms
Wall time: 117 ms


In [19]:
%%time
p8_fast = get_all_perms(8, True)

Mean column values: [3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5]
Column std: [2.29128785 2.29128785 2.29128785 2.29128785 2.29128785 2.29128785
 2.29128785 2.29128785]
CPU times: user 101 ms, sys: 0 ns, total: 101 ms
Wall time: 99.6 ms


In [21]:
%%time
p9 = get_all_perms(9, False)

Mean column values: [4. 4. 4. 4. 4. 4. 4. 4. 4.]
Column std: [2.5819889 2.5819889 2.5819889 2.5819889 2.5819889 2.5819889 2.5819889
 2.5819889 2.5819889]
CPU times: user 726 ms, sys: 0 ns, total: 726 ms
Wall time: 724 ms


In [23]:
%%time
p9 = get_all_perms(9, True)

Mean column values: [4. 4. 4. 4. 4. 4. 4. 4. 4.]
Column std: [2.5819889 2.5819889 2.5819889 2.5819889 2.5819889 2.5819889 2.5819889
 2.5819889 2.5819889]
CPU times: user 581 ms, sys: 0 ns, total: 581 ms
Wall time: 579 ms


In [6]:
from multiperms import *
import numpy as np

In [7]:
from math import factorial

def multinomial_fact(ns):
    result = 1
    sum = 0
    for n in ns:
        result *= factorial(n)
        sum += n
    return factorial(sum) // result

In [8]:
%%timeit
multinomial([2, 5, 10])

1.53 µs ± 19.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
%%timeit
multinomial([10, 5, 2])

2.71 µs ± 45.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
multinomial([2, 2, 2])

90

In [11]:
%%timeit
multinomial_fact([2, 5, 10])

396 ns ± 1.23 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [12]:
%%timeit
multinomial_fact([10, 5, 2])

427 ns ± 15.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [13]:
%%time
N = 10 ** 6
multinomial(np.array([100, 2, N]))

CPU times: user 160 µs, sys: 18 µs, total: 178 µs
Wall time: 183 µs


5385767739532458473930198705053828723360253144523655155268062979484577897907829425062550101338275420640799582526161954989809891207875437088569096390819798968109715908325529654407615618147755031578292158539941608689694714448905275207866200574100659688922083055560106367426108943208849509479818543517740686966631927020953418862956499419512450053998790042810316385724904026415918670182711585716258915869694578535213827865297178128908863594435562129579739526

In [14]:
from itertools import permutations
from more_itertools import distinct_permutations

In [15]:
ns = np.array([3, 4, 5])
print(multinomial(np.copy(ns)))
multiset = []
for i, n in enumerate(ns):
    multiset.extend(n * [i,])
print(multiset)
for perm in sorted(distinct_permutations(multiset)):
    # print(perm)
    index = multiperm2index(np.array(perm), np.copy(ns))
    assert np.allclose(perm, index2multiperm(index, np.copy(ns))) 

27720
[0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2]


In [16]:
%%time
index2multiperm(198, np.array([3, 4, 8]))

CPU times: user 1.28 ms, sys: 103 µs, total: 1.38 ms
Wall time: 905 µs


array([0, 0, 0, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2])